/**
 * fn-alert-weakened
 *
 * Triggered by: vault/claim.weakened
 * Action: High-priority notification when a claim is contradicted
 *         by new evidence. Creates a GitHub issue for investigation.
 */

import { inngest } from "../client.js";
import { exec } from "../helpers.js";

export const alertWeakened = inngest.createFunction(
  {
    id: "alert-weakened",
    retries: 2,
  },
  { event: "vault/claim.weakened" },
  async ({ event, step, logger }) => {
    const {
      claim_id,
      claim_path,
      previous_confidence,
      new_confidence,
      trigger_run_id,
      contradiction,
      boundary_condition_added,
    } = event.data;

    logger.warn(
      `CLAIM WEAKENED: ${claim_id} (${previous_confidence} → ${new_confidence})`
    );

    // Create a GitHub issue for investigation
    const issue = await step.run("create-investigation-issue", async () => {
      const body = `## Claim Weakened

**Claim**: \`${claim_id}\`
**File**: \`${claim_path}\`
**Confidence**: ${previous_confidence} → ${new_confidence}

### Contradiction

${contradiction}

### Boundary condition added

${boundary_condition_added}

### Source run

\`${trigger_run_id}\`

### Action needed

1. Review the contradicting run's data
2. Determine if the claim should be:
   - **Scoped**: add boundary conditions and keep as active
   - **Superseded**: replace with a more precise claim
   - **Retracted**: evidence was flawed
3. Update the claim card accordingly

---
*Auto-generated by SWARM Research OS*`;

      const result = await exec("gh", [
        "issue", "create",
        "--title", `Claim weakened: ${claim_id}`,
        "--body", body,
        "--label", "claim-weakened,investigation,automated",
      ]);

      // Parse issue URL
      const url = result.stdout.trim();
      const issueMatch = url.match(/\/issues\/(\d+)/);
      return {
        issue_number: issueMatch ? parseInt(issueMatch[1], 10) : 0,
        issue_url: url,
      };
    });

    return {
      claim_id,
      issue_number: issue.issue_number,
      issue_url: issue.issue_url,
    };
  },
);
