/**
 * fn-create-pr
 *
 * Triggered by: vault/synthesis.completed
 * Action: Bundle all vault changes from this synthesis pass into a PR.
 */

import { inngest } from "../client.js";
import { exec, createPR, REPO_ROOT } from "../helpers.js";

export const createResultsPR = inngest.createFunction(
  {
    id: "create-pr",
    retries: 2,
    concurrency: { limit: 1 }, // serialize PR creation to avoid branch conflicts
  },
  { event: "vault/synthesis.completed" },
  async ({ event, step, logger }) => {
    const {
      trigger_run_id,
      notes_created,
      claims_updated,
      claims_weakened,
    } = event.data;

    // Skip PR if nothing changed
    if (notes_created === 0 && claims_updated === 0 && claims_weakened === 0) {
      logger.info("No vault changes, skipping PR");
      return { status: "skipped" };
    }

    // 1. Check for unstaged changes in vault/
    const changes = await step.run("detect-changes", async () => {
      const result = await exec("git", [
        "status", "--porcelain", "vault/", "run-index.yaml",
      ]);
      const lines = result.stdout.trim().split("\n").filter(Boolean);
      return lines.map(l => l.slice(3)); // strip status prefix
    });

    if (changes.length === 0) {
      logger.info("No file changes detected, skipping PR");
      return { status: "skipped" };
    }

    // 2. Build PR content
    const prTitle = claims_weakened > 0
      ? `Claim weakened: results from ${trigger_run_id}`
      : `Sweep results: ${trigger_run_id}`;

    const prBody = `## Summary

- **Trigger run**: \`${trigger_run_id}\`
- **Notes created**: ${notes_created}
- **Claims updated**: ${claims_updated}
- **Claims weakened**: ${claims_weakened}

## Files changed

${changes.map(f => `- \`${f}\``).join("\n")}

---
*Auto-generated by SWARM Research OS*`;

    // 3. Create the PR
    const branch = `research-os/${trigger_run_id}`;

    const pr = await step.run("open-pr", async () => {
      return createPR({
        branch,
        title: prTitle,
        body: prBody,
        files: ["vault/", "run-index.yaml"],
      });
    });

    // 4. Emit PR created event
    await step.sendEvent("emit-pr-created", {
      name: "github/pr.created",
      data: {
        pr_number: pr.pr_number,
        pr_url: pr.pr_url,
        title: prTitle,
        trigger_run_id,
        files_changed: changes,
        claims_affected: [], // TODO: extract from synthesis context
      },
    });

    return { pr_number: pr.pr_number, pr_url: pr.pr_url };
  },
);
